### ISSUE TITLE
strict deps

### ISSUE THREAD

**Issue by ngam** [conda-forge/netcdf-fortran-feedstock#70]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Looking at the deps here https://anaconda.org/conda-forge/netcdf-fortran/files.

I see super strict deps. Is this intentional here? Could these be relaxed?

```
hdf5 * mpi_mpich_*, hdf5 >=1.12.1,<1.12.2.0a0 mpi_mpich_*, libgfortran 5.*, libgfortran5 >=11.0.1.dev0, libnetcdf * mpi_mpich_*, libnetcdf >=4.8.1,<4.8.2.0a0 mpi_mpich_*, mpich >=3.4,<3.5.0a0
```

```
hdf5 * mpi_openmpi_*, hdf5 >=1.12.1,<1.12.2.0a0 mpi_openmpi_*, libgfortran 5.*, libgfortran5 >=11.0.1.dev0, libnetcdf * mpi_openmpi_*, libnetcdf >=4.8.1,<4.8.2.0a0 mpi_openmpi_*, openmpi >=4.1.2,<5.0a0
```

```
hdf5 * nompi_*, hdf5 >=1.12.1,<1.12.2.0a0, libgfortran 5.*, libgfortran5 >=11.0.1.dev0, libnetcdf * nompi_*, libnetcdf >=4.8.1,<4.8.2.0a0
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xylar** [comment]
@ngam, I can understand why this might be frustrating.

A big part of why `conda-forge` functions well as an ecosystem is because packages work with compatible versions of libraries.  The strict versions you're seeing (what we refer to as "pins") are related to how frequently these libraries make changes that are not backwards compatible. For some libraries, the version has to be very strict because they have a history of breaking compatibility with every micro-version change.

`conda-forge` keeps track of these common pinned versions here:
https://github.com/conda-forge/conda-forge-pinning-feedstock
More specifically in this file:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

When we want to change one of these pinned versions, we make a pull request to that feedstock to start the process of "migrating" all of the packages that use that dependency over to the new version.  That process can take days to months, depending on the complexity of the migration.

The short answer to your question is that these strict pins are necessary and intentional, and they cannot easily be relaxed.  If one of them is giving you trouble, let us know about the difficulties you're having in more detail and we can see if there's anything we can do to help.  But at most what we will be able to do is make a new version available, not relax the strictness of the pins.

**Comment by ngam** [comment]
@xylar 🌟 thank you so much for your detailed answer!

In short, no, I don't have any particular concerns now. I simply attempted to add netcdf-fortran to a chaotic env and then I realized I was having problems --- I currently have no need for it and so it is okay. I believe the problematic dependency in my case is `hdf5 >=1.12.1,<1.12.2.0a0`  which conflicts with another package that wants `h5py >=3.1.0,<3.2` --- hdf5 and h5py are linked: `h5py >=3.1.0,<3.2` would necessitate `hdf5 >=1.10.6,<1.10.7.0a0`, which breaks the graph.

Anyway, tricky stuff! No worries for my particular case though, just wanted to double check. Thanks again!

**Comment by xylar** [comment]
In your situation, the best thing to do with a chaotic environment is to start over, I'm afraid:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install -y mamba
mamba create -y -n <my_env> hdf5 h5py netcdf-fortran ...
conda activiate <my_env>
```
`mamba` has a much faster solver than `conda` so that's a potentially useful tip for you.

**Comment by xylar** [comment]
I'm going to close this issue for now but feel free to open another one with any more specific problems you run into.
